### ISSUE TITLE
No signature of method: ... .buildBytes() is applicable for argument types

### ISSUE THREAD

**Issue by joergrech** [elastic/elasticsearch-groovy#19]
I'm just starting with this library and I constantly get the following Exception when using elasticsearch-groovy (1.4.2) in a groovy script (ElasticSearchExample.groovy):

``` groovy
groovy.lang.MissingMethodException: No signature of method: ElasticSearchExample.buildBytes() 
is applicable for argument types: (org.elasticsearch.common.xcontent.XContentType$1) values: [JSON]
```

I Googled the problem and found solutions using "GXContentBuilder.rootResolveStrategy = Closure.DELEGATE_FIRST;" but this cannot be used anymore (Class is missing / removed?)

Btw. I grab the following dependencies

```
@Grapes([
    @Grab(group='com.gmongo',           module='gmongo',                version='1.3'),
    @Grab(group='org.elasticsearch',    module='elasticsearch-groovy',  version='1.4.2')
])
```

What can I do to resolve this problem?

**Comment by pickypg** [comment]
@joergrech Gradle 2.4.0 has been released and it appears to have fixed the issue involved with using it within the Groovy Shell.

**Comment by pickypg** [comment]
Note: The above should have ready

> Groovy 2.4.0 has been released...

Sorry for any confusion.
