### ISSUE TITLE
Elastic Documentation

### ISSUE THREAD

**Issue by latusaki** [elastic/elasticsearch-groovy#28]
The documentation found in elastic site https://www.elastic.co/guide/en/elasticsearch/client/groovy-api/master/client.html shows classes GClient and GNode. Although when trying to use those with the dependency shown in the same documentation `elasticsearch-groovy` those classes are not found.
Have posted an SO question about this as well: http://stackoverflow.com/questions/32204552/groovy-elasticsearch-client

Is the documentation wrong, or the dependency linked ?

**Comment by pickypg** [comment]
Commented on the SO post ironically before I noticed this one. This one duplicates #24, which I'm finally getting time to circle around on.
