### ISSUE TITLE
Exception when using grape

### ISSUE THREAD

**Issue by frangarcia** [elastic/elasticsearch-groovy#29]
I am trying to work with the next simple example:

```
@Grapes(
     @Grab(group='org.elasticsearch', module='elasticsearch-groovy', version='1.7.1')
)
import java.lang.String
```

but it throws the next exception

```
Caught: BUG! exception in phase 'conversion' in source unit '/Users/franciscojosegarciarico/Desktop/elasticsearch.groovy' # Licensed to the Apache Software Foundation (ASF) under one or more
BUG! exception in phase 'conversion' in source unit '/Users/franciscojosegarciarico/Desktop/elasticsearch.groovy' # Licensed to the Apache Software Foundation (ASF) under one or more
Caused by: java.lang.ClassNotFoundException: # Licensed to the Apache Software Foundation (ASF) under one or more
```

I am using Groovy 2.1.5 and running the code in command line but also using groovyConsole.

**Comment by pickypg** [comment]
Thanks for the report @frangarcia. Can you attach the `elasticsearch.groovy` file in question? It looks like there may be an invalid comment along the time of the file.

**Comment by pickypg** [comment]
(Or post it in a Gist if it's relatively large)

**Comment by frangarcia** [comment]
That was the only code:

https://gist.github.com/frangarcia/5ec560a13b269c20ef52

**Comment by pickypg** [comment]
I've confirmed this locally fails with just running Groovy running 2.4.1 locally:

```bash
$ groovy elasticsearch.groovy
Caught: BUG! exception in phase 'conversion' in source unit '/Users/pickypg/Dev/es/es-groovy/tmp/elasticsearch.groovy' # Licensed to the Apache Software Foundation (ASF) under one or more
BUG! exception in phase 'conversion' in source unit '/Users/pickypg/Dev/es/es-groovy/tmp/elasticsearch.groovy' # Licensed to the Apache Software Foundation (ASF) under one or more
Caused by: java.lang.ClassNotFoundException: # Licensed to the Apache Software Foundation (ASF) under one or more
```

This seems to be a bug in Grape, which is more catchable if you use the method to manually `grab`:

```groovy
import groovy.grape.Grape

try {
  Grape.grab(group: 'org.elasticsearch', module: 'elasticsearch-groovy', version: '1.7.1')
}
catch (Throwable t) {
  t.printStackTrace()
}
```

This leads to the full exception stacktrace (included in the link below):

```
java.lang.ClassNotFoundException: # Licensed to the Apache Software Foundation (ASF) under one or more
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        ...
```

I could not find a workaround for this issue, so [I created a bug report for Groovy with `GROOVY-7613`](https://issues.apache.org/jira/browse/GROOVY-7613).

**Comment by frangarcia** [comment]
I am not 100% sure it is a Grape bug as this example is not throwing any exception:

```
@Grapes(
     @Grab(group='org.twitter4j', module='twitter4j-core', version='4.0.4') 
)
import java.lang.String 
```

**Comment by pickypg** [comment]
@frangarcia Understood. I also tested it with the non-Groovy Elasticsearch jar (`module='elasticsearch'`) and that also worked.

I am pretty confident that this has to do with the fact that the Groovy jar includes [extension modules](https://github.com/elastic/elasticsearch-groovy/blob/master/src/main/resources/META-INF/services/org.codehaus.groovy.runtime.ExtensionModule) (note the first line). [I have had different problems in the past with `Grape` relating to extension modules](https://github.com/elastic/elasticsearch-groovy/issues/19#issuecomment-68199647), but this one is a bit different.

**Comment by pickypg** [comment]
Actually, I just noticed that while the comment _style_ is the same, the comment itself is not. I'm taking a second look.

**Comment by pickypg** [comment]
This error seems to be happening from the Groovy dependency within the `META-INF` directory.

**Comment by frangarcia** [comment]
If we exclude groovy-all it seems to be working

```@Grab(group='org.elasticsearch', module='elasticsearch-groovy', version='1.7.1') 
@GrabExclude('org.codehaus.groovy:groovy-all')    
import java.lang.String

println "hola"```

**Comment by pickypg** [comment]
Yeah, it looks like that is a necessary thing to do. I'll update the issue so that Grab itself excludes Groovy as a dependency.

Perhaps I need to rethink my Gradle dependency so that Groovy is runtime (but it certainly needs to compile with it). I'll snoop around to see how normal that is within the community.

**Comment by frangarcia** [comment]
Great! Thanks Chris!

**Comment by pickypg** [comment]
I've looked into this a bit (very actively at first, and now much less so). I think that I need to retool my build to mark this as "provided" using the Netflix's Gradle build tools. I should have some time to do this soon, but it may be forced upon me by changes required to get tests running in ES 2.2.
