### ISSUE TITLE
Build of 2.1 fails on AmazonLinux / CentOS

### ISSUE THREAD

**Issue by joergrech** [elastic/elasticsearch-groovy#32]
I tried to build version 2.1.1-SNAPSHOT on a AWS Linux machine but if fails - probable due to the shutdown of codehaus:

```
gradle clean installDist

:clean
:grails:clean
:compileJava UP-TO-DATE
:compileGroovy

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not resolve org.elasticsearch:elasticsearch:2.1.1-SNAPSHOT.
  Required by:
      org.elasticsearch:elasticsearch-groovy:2.1.1-SNAPSHOT
   > Could not resolve org.elasticsearch:elasticsearch:2.1.1-SNAPSHOT.
      > Unable to load Maven meta-data from http://repository.codehaus.org/org/elasticsearch/elasticsearch/2.1.1-SNAPSHOT/maven-metadata.xml.
         > Could not GET 'http://repository.codehaus.org/org/elasticsearch/elasticsearch/2.1.1-SNAPSHOT/maven-metadata.xml'.
            > repository.codehaus.org: Name or service not known

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.676 secs
```

Is there any other way to get a version that works with Elasticsearch 2.1.1?

**Comment by pickypg** [comment]
This was on me rather that codehaus. They haven't changed their group name yet. The lack of an ES 2.1.1-SNAPSHOT (after the main release, the snapshots eventually go away).

For the record, if you ever need to build a release, but only have a SNAPSHOT, then just chop off the "-SNAPSHOT" from the ES versions and make sure that the Lucene version is correct (it's only used for tests).

This should be resolved by me pushing the latest versions.
