### ISSUE TITLE
Publish GroovyDocs

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch-groovy#34]
I should find a place to publish the GroovyDocs for the Groovy client.

They are currently uploaded with each release ([feel free to download the groovydoc jar and extract its contents](http://search.maven.org/#artifactdetails%7Corg.elasticsearch%7Celasticsearch-groovy%7C2.1.2%7Cjar)), but not automatically added to any site.

**Comment by tingletech** [comment]
docs are also here: https://github.com/elastic/elasticsearch-groovy/blob/master/docs/quickstart.asciidoc

**Comment by kokeksibir** [comment]
Hello, as a "super confused" one, I could not figure it out.

I have compiled client for elasticsearch 5.2.2, but I get "unable to resolve class" when I follow directions of both [outdated docs](https://github.com/elastic/elasticsearch-groovy/blob/master/docs/quickstart.asciidoc) and [elasticsearch's groovy api docs](https://www.elastic.co/guide/en/elasticsearch/client/groovy-api/current/client.html).

Could you please advise me the correct method to initialize client?
