### ISSUE TITLE
Unable to load extension classes Warnings

### ISSUE THREAD

**Issue by jadelus** [elastic/elasticsearch-groovy#36]
I'm trying to integrate version 2.1.2 with Grails 2.5.4 and I'm seeing the following output when building the Grails app:

`WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.ClosureExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.ListenableActionFutureExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.admin.cluster.repositories.put.PutRepositoryRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.admin.cluster.settings.ClusterUpdateSettingsRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.admin.cluster.snapshots.create.CreateSnapshotRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.admin.cluster.snapshots.restore.RestoreSnapshotRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.admin.indices.create.CreateIndexRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.admin.indices.mapping.put.PutMappingRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.admin.indices.settings.put.UpdateSettingsRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.count.CountRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.deletebyquery.DeleteByQueryRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.explain.ExplainRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.fieldstats.FieldStatsRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.index.IndexRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.indexedscripts.put.PutIndexedScriptRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.percolate.PercolateRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.search.SearchRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.update.UpdateRequestExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.client.AdminClientExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.client.ClientExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.client.ClusterAdminClientExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.client.IndicesAdminClientExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.node.NodeBuilderExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.node.NodeExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.common.settings.SettingsBuilderExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.common.xcontent.XContentBuilderExtensions]
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.common.settings.SettingsStaticExtensions]`

I have read the closed issue #30 (Upload 2.1.0 artifacts to mavencentral) but this looks to be a more fundamental issue (perhaps misconfiguration on my part?).

Any help gratefully appreciated.

**Comment by pickypg** [comment]
Hi @jadelus, can you show how you're referencing 2.1.2 in your Grails build?

**Comment by jadelus** [comment]
Hi, thanks for the fast response. This is what I have in BuildConfig:

`runtime group: 'org.elasticsearch', name: 'elasticsearch-groovy', version: '2.1.2', classifier: 'grails'`

per your docs.

**Comment by pickypg** [comment]
Hmmm. It looks like it cannot apply them because it's missing the classes (generally what the warning means).

Can you run this and verify that the Elasticsearch jar (not the Groovy one) is in the dependency you report?

```
grails dependency-report runtime
```

**Comment by jadelus** [comment]
Looks like it's there:

`+--- org.elasticsearch:elasticsearch-groovy:2.1.2
|    \--- org.codehaus.groovy:groovy-all:2.4.4
|   ** \--- org.elasticsearch:elasticsearch:2.1.2**
|         \--- org.apache.lucene:lucene-core:5.3.1
|         \--- org.apache.lucene:lucene-backward-codecs:5.3.1
|         \--- org.apache.lucene:lucene-analyzers-common:5.3.1
|         \--- org.apache.lucene:lucene-queries:5.3.1
|         \--- org.apache.lucene:lucene-memory:5.3.1
|         \--- org.apache.lucene:lucene-highlighter:5.3.1
|         \--- org.apache.lucene:lucene-queryparser:5.3.1
|              \--- org.apache.lucene:lucene-sandbox:5.3.1
|         \--- org.apache.lucene:lucene-suggest:5.3.1
|              \--- org.apache.lucene:lucene-misc:5.3.1
|         \--- org.apache.lucene:lucene-join:5.3.1
|              \--- org.apache.lucene:lucene-grouping:5.3.1
|         \--- org.apache.lucene:lucene-spatial:5.3.1
|              \--- org.apache.lucene:lucene-spatial3d:5.3.1
|              \--- com.spatial4j:spatial4j:0.4.1
|         \--- com.google.guava:guava:18.0
|         \--- com.carrotsearch:hppc:0.7.1
|         \--- org.joda:joda-convert:1.2
|         \--- com.fasterxml.jackson.core:jackson-core:2.6.2
|         \--- com.fasterxml.jackson.dataformat:jackson-dataformat-smile:2.6.2
|         \--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.6.2
|              \--- org.yaml:snakeyaml:1.15
|         \--- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.6.2
|         \--- io.netty:netty:3.10.5.Final
|         \--- com.ning:compress-lzf:1.0.2
|         \--- com.tdunning:t-digest:3.0
|         \--- org.hdrhistogram:HdrHistogram:2.1.6
|         \--- commons-cli:commons-cli:1.3.1
|         \--- com.twitter:jsr166e:1.1.0`

**Comment by jadelus** [comment]
@pickypg I managed to get past this by placing elasticsearch-groovy-2.1.3-SNAPSHOT.jar in my grails lib directory. Now I just have the understood `Unable to load extension class [org.elasticsearch.groovy.action.deletebyquery.DeleteByQueryRequestExtensions]`. So it looks like I can move forward.   Strange how referencing the dependency in my BuildConfig file didn't pull in those classes.

Thanks for your help anyhow.

**Comment by pickypg** [comment]
You could try switching it from `runtime` to `compile`. It sounds like it's a bug that it's not placing the jars there for you, but I assume that `compile` will force it?

Or perhaps the command that you're using to build the code isn't actually hitting the `runtime` step? This should get much simpler as they begin using Gradle with the 3.x version of Grails.

**Comment by jadelus** [comment]
Yeah it's pretty convoluted what with all the the versions (for Grails, Grails' Groovy, Elasticsearch, Elasticsearch's Groovy etc., not to mention AWS us providing clusters with 1.6 !! - go figure).  I gave up on the Grails elasticsearch plugin as it was too much to get working. Hopefully I can get going with the Groovy Client 2.1.3 and an account on Elasticsearch cloud.

Thanks again!

**Comment by pickypg** [comment]
I'm not trying to get the last word, I promise. :)

FYI, ES 2.1.3 is not released. You should use ES Groovy 2.1.2 with ES 2.1.2.
