### ISSUE TITLE
milestone for elasticsearch v5 compat

### ISSUE THREAD

**Issue by jamesbeedy** [elastic/elasticsearch-groovy#37]
Is there a current milestone for es v5 compat?

**Comment by pickypg** [comment]
Yes. I have struggled to get the 2.x build to work, but the 5.x build is a big change and I should be able to finish it soon.

Stay tuned on this issue.

**Comment by jamesbeedy** [comment]
@pickypg thats great news! will do

**Comment by pickypg** [comment]
This is awaiting https://github.com/elastic/elasticsearch/pull/21773

**Comment by enp** [comment]
I see changes in elastic/elasticsearch#21773 which can fix this issue. Is it possible to prepare 5.x build (maybe with some issues) in any case simple to try to 5.x via groovy script?

**Comment by pickypg** [comment]
I have `master` building against Elasticsearch's master again. I need to get the tests in the same state, and then I can backport/update through 5.0.0. Once done, the release cadence should return to what it was before the security manager blocked it from running.

**Comment by oyiadom** [comment]
@pickypg have you been able to make progress with the tests?  Can my team members or I assist with the update in any way?  We are currently using the Groovy API for Elasticsearch and are trying to decide whether we should switch to using the Java API for Elasticsearch 5 (i.e. since the Java API is currently available in Maven).

**Comment by erichmx** [comment]
@pickypg any news on this? Does it make sense to have the security manager enabled for when testing the client?

I've been trying to use this client but I get the same errors that I get when trying to run the tests: 

groovy.lang.MissingMethodException: No signature of method: org.elasticsearch.action.search.SearchRequest.source() is applicable for argument types: ([B) values: [[123, 34, 113, 117, 101, 114, 121, 34, 58, 123, 34, 109, 97, ...]]
   > Possible solutions: source(), source(org.elasticsearch.search.builder.SearchSourceBuilder), source(groovy.lang.Closure), collect(), use([Ljava.lang.Object;)

As if the extension methods were not being "wired"
