### ISSUE TITLE
Extension Modules vs maven-shade-plugin

### ISSUE THREAD

**Issue by yuri1969** [elastic/elasticsearch-groovy#39]
I use `v2.1.2` in my MVN project. _Groovy Extensions_ supplied by `elasticsearch-groovy` work fine in IDE, although when I try to a built _fat JAR_ produced by `Maven Shade plugin` with `ServicesResourceTransformer` enabled it fails.

Running following snippets end up in **No signature of method:  org.elasticsearch.node.NodeBuilder.settings() ... closure** respectively **Settings.settingsBuilder()** .
```
nodeBuilder().settings {
                cluster {
                    name = "foo"
                ...
}
```
or
```
Settings.settingsBuilder {
                cluster {
                    name = "foo"
                ...
```

**It seems it ends up invoking a _Java_ `settings()` method instead of the one supplied by _Groovy Extensions_ `NodeBuilderExtensions`.**

In the resulting fat JAR I can see there is a file `META-INF/services/org.codehaus.groovy.runtime.ExtensionModule` which contains merged Extensions from modules:

- `groovy-all`
- `elasticsearch-groovy-module`

Is it even possible to have multiple module references in that file?

**Comment by pickypg** [comment]
This is most likely the same problem that occurs when you have SPI definitions for the same class. I do _not_ think that Groovy supports multiple modules in the same file, nor do I believe that it accepts multiple versions of the same properties being set.

The only solution would therefore be to _not_ include `elasticsearch-groovy` in the shaded / fat jar or somehow get the shading process to more properly merge the properties that exist there.

**Comment by yuri1969** [comment]
@pickypg :( That's what I thought.

The shade plugin simply creates `META-INF/services/*` files for each JAR's service. But both `groovy-all` and `elasticsearch-groovy-module` happen to employ the same `org.codehaus.groovy.runtime.ExtensionModule` file. Thus it adds both JAR references into this single file...

**Comment by pickypg** [comment]
Good luck with the issue @yuri1969.

For what it's worth, Elasticsearch moved away from shaded jars in Elasticsearch 2.0 because it proved to be problematic for similar reasons as this (not to mention you often end up creating an extremely large classpath unnecessarily).

**Comment by yuri1969** [comment]
Just for the record:
I've solved this by using _Gradle_ plugin called [_Shadow_](http://imperceptiblethoughts.com/shadow/). It features support of service resource transformation and on top of that it has a option for handling of Groovy Extensions.

Ofc, it required to migrate from _Maven_ to _Gradle_...
