### ISSUE TITLE
Groovy API for ES 5.x

### ISSUE THREAD

**Issue by oyiadom** [elastic/elasticsearch-groovy#40]
Do you know when the Groovy API for ES 5.x will be available in Maven?  Contrary to what is [written in the documentation on the Elasticsearch Website](https://www.elastic.co/guide/en/elasticsearch/client/groovy-api/current/_preface.html), the latest version of the API that exists in Maven is [2.1.2](https://mvnrepository.com/artifact/org.elasticsearch/elasticsearch-groovy).  Even the [information in this GitHub repository](https://github.com/elastic/elasticsearch-groovy#versions) about building the 5.x API from source references the 2.1.2 version of the API.

**Comment by pickypg** [comment]
Hi @oyiadom, #37 is all about ES 5.0 compatibility.

I have the code compiling for 5.x compatibility, but I do not have all of the tests passing yet because of the security manager. I have been slowly getting compatibility there though.
